RAW_SCHEMA_VERSION = "raw_v1"
FEATURE_SCHEMA_VERSION = "feature_v1"
TARGET_SCHEMA_VERSION = "target_v1"
DATASET_SCHEMA_VERSION = "dataset_v1"

DEFAULT_TIMEFRAME = "5m"
DEFAULT_HORIZON_BARS = 12
DEFAULT_TIMEZONE = "Europe/Moscow"

