ALTER TABLE assets ADD COLUMN IF NOT EXISTS figi TEXT NOT NULL DEFAULT '';
ALTER TABLE assets ADD COLUMN IF NOT EXISTS instrument_uid TEXT NOT NULL DEFAULT '';
ALTER TABLE assets ADD COLUMN IF NOT EXISTS class_code TEXT NOT NULL DEFAULT '';
ALTER TABLE assets ADD COLUMN IF NOT EXISTS instrument_type TEXT NOT NULL DEFAULT '';
ALTER TABLE assets ADD COLUMN IF NOT EXISTS lot INTEGER NOT NULL DEFAULT 1;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS currency TEXT NOT NULL DEFAULT 'rub';
ALTER TABLE assets ADD COLUMN IF NOT EXISTS api_trade_available BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS first_1min_candle_date TIMESTAMPTZ;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS first_1day_candle_date TIMESTAMPTZ;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS model_supported BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_assets_instrument_uid ON assets (instrument_uid);
CREATE INDEX IF NOT EXISTS idx_assets_figi ON assets (figi);
