ALTER TABLE notification_rules_v2 
ADD COLUMN IF NOT EXISTS target_indicator TEXT,
ADD COLUMN IF NOT EXISTS operator TEXT,
ADD COLUMN IF NOT EXISTS secondary_threshold NUMERIC(24,8),
ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS trigger_mode TEXT NOT NULL DEFAULT 'once',
ADD COLUMN IF NOT EXISTS delivery_channels TEXT[] NOT NULL DEFAULT '{app}';
